"""Add completed column to ExerciseAttempt

Revision ID: c47e2439a355
Revises: 
Create Date: 2025-03-21 20:26:36.762107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47e2439a355'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_attempt', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
