"""Add type column to Exercise model

Revision ID: cb3da7a6e921
Revises: cfa790756b6c
Create Date: 2025-05-09 23:29:44.184769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb3da7a6e921'
down_revision = 'cfa790756b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))
        batch_op.drop_column('image_path')
        batch_op.drop_column('max_attempts')
        batch_op.drop_column('description')
        batch_op.drop_column('exercise_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_type', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('max_attempts', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###
